import type { VideoItem } from "./types";

export const mockVideos: VideoItem[] = [
	{
		videoId: "1",
		authorId: "author-1",
		nickname: "野生阿睿",
		desc: "很低脂的一男的。",
		createdAt: "2025-12-22 02:30:49",
		videoLocalCover: "/static/images/default.jpg",
		videoLocalPlayAddr: "/static/video/default.mp4",
		videoRawPlayAddr: "/static/video/default.mp4",
		videoUrl: "/content/1.html",
		authorUrl: "/author/author-1/1",
	},
	{
		videoId: "2",
		authorId: "author-2",
		nickname: "小胖胖胖胖",
		desc: "一紧张 动作忘记了。",
		createdAt: "2025-12-21 13:34:32",
		videoLocalCover: "/static/images/default.jpg",
		videoLocalPlayAddr: "/static/video/default.mp4",
		videoRawPlayAddr: "/static/video/default.mp4",
		videoUrl: "/content/2.html",
		authorUrl: "/author/author-2/1",
	},
	{
		videoId: "3",
		authorId: "author-3",
		nickname: "王林江",
		desc: "前刺。",
		createdAt: "2025-12-21 13:14:24",
		videoLocalCover: "/static/images/default.jpg",
		videoLocalPlayAddr: "/static/video/default.mp4",
		videoRawPlayAddr: "/static/video/default.mp4",
		videoUrl: "/content/3.html",
		authorUrl: "/author/author-3/1",
	},
	{
		videoId: "4",
		authorId: "author-4",
		nickname: "好事花生",
		desc: "前奏一响 回忆登场 #心做的 #不随风 #猛男",
		createdAt: "2025-12-21 09:50:41",
		videoLocalCover: "/static/images/default.jpg",
		videoLocalPlayAddr: "/static/video/default.mp4",
		videoRawPlayAddr: "/static/video/default.mp4",
		videoUrl: "/content/4.html",
		authorUrl: "/author/author-4/1",
	},
	{
		videoId: "5",
		authorId: "author-5",
		nickname: "柯廷云",
		desc: "一觉醒来我内蒙人了…",
		createdAt: "2025-12-21 07:06:19",
		videoLocalCover: "/static/images/default.jpg",
		videoLocalPlayAddr: "/static/video/default.mp4",
		videoRawPlayAddr: "/static/video/default.mp4",
		videoUrl: "/content/5.html",
		authorUrl: "/author/author-5/1",
	},
	{
		videoId: "6",
		authorId: "author-6",
		nickname: "沙糖桔（番桔）",
		desc: "🍊 来一段 热热身 #素古舞 #民族舞 #抖音热门 舞蹈计划。",
		createdAt: "2025-12-21 07:02:36",
		videoLocalCover: "/static/images/default.jpg",
		videoLocalPlayAddr: "/static/video/default.mp4",
		videoRawPlayAddr: "/static/video/default.mp4",
		videoUrl: "/content/6.html",
		authorUrl: "/author/author-6/1",
	},
];

export const totalPages = 5;
